[package]
name = "rustfolio"
version = "0.1.0"
edition = "2021"

[dependencies]
piechart = { git = "https://github.com/Melesar/piechart" }
xdg = "2.0"
args = "2.0"
getopts = "0.2.21"
csv = "1.1"
crossterm = "0.19.0"
